version: '3'

services:
  postgres:
    image: 'postgres:12.2'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/onebitchat'
    volumes_from:
    - box
    env_file:
      - '.env'

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  postgres:
  box: